#!/bin/bash

if [[ -z $(which inkscape) ]]
then
        echo "Error, inkscape not avaialbe" >&2
        exit
fi

if [[ $# -lt 1 ]] || [[ ! -s $1 ]]
then
        echo "Error, valid input file must be provided." >&2
        echo "Usage: svg2pdf filename.svg [filename.pdf]" >&2
        exit
fi
input=$1

if [ $# -ge 2 ]
then
        output=$2
else
        output=${input%.svg}.pdf
fi

inkscape --export-pdf=${output} ${input}
